version: "3"
services:
  zookeeper:
    container_name: zookeeper
    image: debezium/zookeeper:${DEBEZIUM_VERSION}
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
  kafka:
    container_name: kafka
    image: debezium/kafka:${DEBEZIUM_VERSION}
    ports:
      - 9092:9092
    links:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
      - ADVERTISED_LISTENERS=PLAINTEXT://host.docker.internal:9092
      - LISTENERS=PLAINTEXT://:9092
  consumer:
    container_name: consumer
    image: debezium/kafka-connect-consumer:${DEBEZIUM_VERSION}
    build:
      context: kafka-connect-consumer
      args:
        DEBEZIUM_VERSION: ${DEBEZIUM_VERSION}
    ports:
      - 5005:5005
      - 1976:1976
      - 8083:8083
    links:
      - kafka
      - oracle-db-source
      - oracle-db-target
    volumes:
      - ${PROJECT_PATH}/kafka-connect-consumer/oracle_instantclient/ojdbc8.jar /kafka/libs
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
      - LD_LIBRARY_PATH=/instant_client
  producer:
    container_name: producer
    image: debezium/kafka-connect-producer:${DEBEZIUM_VERSION}
    build:
      context: kafka-connect-producer
      args:
        DEBEZIUM_VERSION: ${DEBEZIUM_VERSION}
    ports:
      - 5005:5005
      - 1976:1976
      - 8084:8083
    links:
      - kafka
      - oracle-db-source
      - oracle-db-target
    volumes:
      - ${PROJECT_PATH}/kafka-connect-producer/oracle_instantclient/ojdbc8.jar /kafka/libs
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
      - LD_LIBRARY_PATH=/instant_client
  oracle-db-source:
    container_name: oracle-db-source
    hostname: oracle-db-source
    image: oracleinanutshell/oracle-xe-11g:latest
    ports:
      - 1521:1521
      - 5500:5500
    volumes:
      - ${PROJECT_PATH}/ora-init:/docker-entrypoint-initdb.d
    environment:
      - ORACLE_ALLOW_REMOTE=true
      - ORACLE_HOME=/u01/app/oracle/product/11.2.0/xe
  oracle-db-target:
    container_name: oracle-db-target
    hostname: oracle-db-target
    image: oracleinanutshell/oracle-xe-11g:latest
    ports:
      - 3042:1521
      - 3300:5500
    volumes:
      - ${PROJECT_PATH}/ora-target-init:/docker-entrypoint-initdb.d
    environment:
      - ORACLE_ALLOW_REMOTE=true
      - ORACLE_HOME=/u01/app/oracle/product/11.2.0/xe
